version: "3"

services:
    client:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./serve:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf